version: '3.9'

services:
  authboard_postgres:
    image: postgres:15
    container_name: authboard_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - authboard_network

  tenant_service:
    build:
      context: ./tenant_service
      dockerfile: Dockerfile
    container_name: tenant_service
    depends_on:
      - authboard_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - authboard_network

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    depends_on:
      - authboard_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - authboard_network

volumes:
  postgres_data:

networks:
  authboard_network:
    driver: bridge
