// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/rbacpb/rbac.proto

package rbacpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *AssignRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleRequest) Reset() {
	*x = RemoveRoleRequest{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleRequest) ProtoMessage() {}

func (x *RemoveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RemoveRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleResponse) Reset() {
	*x = RemoveRoleResponse{}
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleResponse) ProtoMessage() {}

func (x *RemoveRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacpb_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleResponse.ProtoReflect.Descriptor instead.
func (*RemoveRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacpb_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_rbacpb_rbac_proto protoreflect.FileDescriptor

const file_proto_rbacpb_rbac_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rbacpb/rbac.proto\x12\x04rbac\"I\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"/\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"@\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\".\n" +
	"\x12AssignRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"@\n" +
	"\x11RemoveRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\".\n" +
	"\x12RemoveRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd3\x01\n" +
	"\vrbacService\x12B\n" +
	"\vCheckAccess\x12\x18.rbac.CheckAccessRequest\x1a\x19.rbac.CheckAccessResponse\x12?\n" +
	"\n" +
	"AssignRole\x12\x17.rbac.AssignRoleRequest\x1a\x18.rbac.AssignRoleResponse\x12?\n" +
	"\n" +
	"RemoveRole\x12\x17.rbac.RemoveRoleRequest\x1a\x18.rbac.RemoveRoleResponseB8Z6github.com/krishnachowdaryvanam/authboard/proto/rbacpbb\x06proto3"

var (
	file_proto_rbacpb_rbac_proto_rawDescOnce sync.Once
	file_proto_rbacpb_rbac_proto_rawDescData []byte
)

func file_proto_rbacpb_rbac_proto_rawDescGZIP() []byte {
	file_proto_rbacpb_rbac_proto_rawDescOnce.Do(func() {
		file_proto_rbacpb_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbacpb_rbac_proto_rawDesc), len(file_proto_rbacpb_rbac_proto_rawDesc)))
	})
	return file_proto_rbacpb_rbac_proto_rawDescData
}

var file_proto_rbacpb_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_rbacpb_rbac_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),  // 0: rbac.CheckAccessRequest
	(*CheckAccessResponse)(nil), // 1: rbac.CheckAccessResponse
	(*AssignRoleRequest)(nil),   // 2: rbac.AssignRoleRequest
	(*AssignRoleResponse)(nil),  // 3: rbac.AssignRoleResponse
	(*RemoveRoleRequest)(nil),   // 4: rbac.RemoveRoleRequest
	(*RemoveRoleResponse)(nil),  // 5: rbac.RemoveRoleResponse
}
var file_proto_rbacpb_rbac_proto_depIdxs = []int32{
	0, // 0: rbac.rbacService.CheckAccess:input_type -> rbac.CheckAccessRequest
	2, // 1: rbac.rbacService.AssignRole:input_type -> rbac.AssignRoleRequest
	4, // 2: rbac.rbacService.RemoveRole:input_type -> rbac.RemoveRoleRequest
	1, // 3: rbac.rbacService.CheckAccess:output_type -> rbac.CheckAccessResponse
	3, // 4: rbac.rbacService.AssignRole:output_type -> rbac.AssignRoleResponse
	5, // 5: rbac.rbacService.RemoveRole:output_type -> rbac.RemoveRoleResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rbacpb_rbac_proto_init() }
func file_proto_rbacpb_rbac_proto_init() {
	if File_proto_rbacpb_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbacpb_rbac_proto_rawDesc), len(file_proto_rbacpb_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbacpb_rbac_proto_goTypes,
		DependencyIndexes: file_proto_rbacpb_rbac_proto_depIdxs,
		MessageInfos:      file_proto_rbacpb_rbac_proto_msgTypes,
	}.Build()
	File_proto_rbacpb_rbac_proto = out.File
	file_proto_rbacpb_rbac_proto_goTypes = nil
	file_proto_rbacpb_rbac_proto_depIdxs = nil
}
