// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/eventpb/event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "user_created", "tenant_deleted"
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON or serialized data as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_proto_eventpb_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventpb_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventpb_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_proto_eventpb_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventpb_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventpb_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_eventpb_event_proto protoreflect.FileDescriptor

const file_proto_eventpb_event_proto_rawDesc = "" +
	"\n" +
	"\x19proto/eventpb/event.proto\x12\x05event\"G\n" +
	"\fEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\")\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2I\n" +
	"\fEventService\x129\n" +
	"\fPublishEvent\x12\x13.event.EventRequest\x1a\x14.event.EventResponseB9Z7github.com/krishnachowdaryvanam/authboard/proto/eventpbb\x06proto3"

var (
	file_proto_eventpb_event_proto_rawDescOnce sync.Once
	file_proto_eventpb_event_proto_rawDescData []byte
)

func file_proto_eventpb_event_proto_rawDescGZIP() []byte {
	file_proto_eventpb_event_proto_rawDescOnce.Do(func() {
		file_proto_eventpb_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eventpb_event_proto_rawDesc), len(file_proto_eventpb_event_proto_rawDesc)))
	})
	return file_proto_eventpb_event_proto_rawDescData
}

var file_proto_eventpb_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_eventpb_event_proto_goTypes = []any{
	(*EventRequest)(nil),  // 0: event.EventRequest
	(*EventResponse)(nil), // 1: event.EventResponse
}
var file_proto_eventpb_event_proto_depIdxs = []int32{
	0, // 0: event.EventService.PublishEvent:input_type -> event.EventRequest
	1, // 1: event.EventService.PublishEvent:output_type -> event.EventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_eventpb_event_proto_init() }
func file_proto_eventpb_event_proto_init() {
	if File_proto_eventpb_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eventpb_event_proto_rawDesc), len(file_proto_eventpb_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eventpb_event_proto_goTypes,
		DependencyIndexes: file_proto_eventpb_event_proto_depIdxs,
		MessageInfos:      file_proto_eventpb_event_proto_msgTypes,
	}.Build()
	File_proto_eventpb_event_proto = out.File
	file_proto_eventpb_event_proto_goTypes = nil
	file_proto_eventpb_event_proto_depIdxs = nil
}
